# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'psych', '~> 3.3', '>= 3.3.2'
gem 'safe_yaml', '~> 1.0', '>= 1.0.5'