# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'activesupport', '~> 6.1', '>= 6.1.4.1'
gem 'rexml', '~> 3.2', '>= 3.2.5'
gem 'ox', '~> 2.14', '>= 2.14.5'
gem 'plist', '~> 3.6'